#!/usr/bin/env bash

# Automated installer for vedantrathore/dotfiles using dotbot

function pecho() {
    local PRINT_COLOR=6
    if [[ ! -z "$2" ]] ; then
        PRINT_COLOR=$2
    fi

    echo -ne "$(tput setaf "${PRINT_COLOR}")$1$(tput sgr0)"
}

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG="install.conf.yaml"
DOTBOT_DIR="vendor/github/dotbot"
DOTBOT_BIN="bin/dotbot"

###############################################################################
# dotbot install
###############################################################################

pecho "Linking with dotbot:\n"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

###############################################################################
# Powerline fonts
###############################################################################

pecho "Would you like to install powerline fonts ? [y/N] "
read -r response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
    source ${BASEDIR}/vendor/github/fonts/install.sh
else
    echo "Skipped installation of powerline fonts"
fi

###############################################################################
# Install zsh (oh-my-zsh) + plugins + themes
###############################################################################

pecho "Installing zsh (oh-my-zsh) + plugins + themes:\n"

if [ ! -d $HOME/.oh-my-zsh ] ; then
    
    echo "Installing Oh My Zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    
    source $HOME/.zshrc
else
    echo "Oh My Zsh already installed"
fi

###############################################################################
# Update Vim plugins
###############################################################################

pecho "Cleaning/Installing/Updating Vim plugins:\n"

if [ ! -e ~/.vim/autoload/plug.vim ]; then
    curl -fs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' > ~/.vim/autoload/plug.vim
fi

vim -E -s -u $MYVIMRC \
 +source $MYVIMRC \
 +PlugClean \
 +PlugUpdate \
 +PlugInstall \
 +qall \

###############################################################################
# Install brew + formulae (macOS only)
###############################################################################

## abort if not macOS
[[ "$OSTYPE" =~ ^darwin ]] || exit 0

## install homebrew + formulae?
pecho "Would you like to install Homebrew (http://brew.sh) + my formulae + configure macos settings? [y/N] "
read -r response ; tput sgr0
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]] ; then
    echo "Installing brew and formulae (z, fzf, thefuck, etc...):"

    # brew installed?
    which -s brew
    if [[ $? != 0 ]] ; then
        # install Homebrew
        echo "Installing brew:"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    else
        echo "Brew already installed. Let's make sure your formulae are up to date:"
        brew update
        brew upgrade
    fi

    # Double check we've installed brew correctly
    if command -v brew >/dev/null 2>&1 ; then
      echo "Installing brew formulae:"

      # Install GNU core utilities (those that come with macOS are outdated)
      # Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`
      brew install coreutils
      brew install findutils
      brew install gnu-tar
      brew install gnu-sed
      brew install gawk
      brew install gnutls
      brew install gnu-indent
      brew install gnu-getopt
      brew install grep

      # Install some other useful utilities like `sponge`.
      brew install moreutils

      # Install GNU `sed`, overwriting the built-in `sed`.
      brew install gnu-sed 

      # Install `wget` with IRI support.
      brew install wget 
      
      # Install a modern version of Zsh.
      brew install zsh

      # Install GnuPG to enable PGP-signing commits.
      brew install gnupg

      # Install more recent versions of some macOS tools.
      brew install vim
      brew install openssh
      brew install screen
      brew install cmake

      # Install font tools.
      brew tap bramstein/webfonttools
      brew tap homebrew/cask-fonts
      brew install sfnt2woff
      brew install sfnt2woff-zopfli
      brew install woff2
      brew install fontconfig
      brew install --cask font-fira-code

      # Misc useful formulae (brew list -la | awk '{a="brew install "$9; print a}' | pbcopy)
      brew install ack
      brew install findutils
      brew install fpp
      brew install git
      brew install git-extras
      brew install htop-osx
      brew install httpie
      brew install nvm
      brew install openssl
      brew install python
      brew install python3
      brew install thefuck
      brew install tmux
      brew install tree
      brew install zxoide
      brew install eza
      brew install bat
      brew install freetype
      brew install go
      brew install http-server
      brew install jq
      brew install gh
      brew install libevent
      brew install libmpc
      brew install libpng
      brew install libtiff
      brew install libtool
      brew install m-cli
      brew install neofetch
      brew install node
      brew install readline
      brew install yarn
      brew install diff-so-fancy
      brew install pwgen
      brew install pre-commit
      brew install MonitorControl


      # Useful macos apps
      brew install --cask keepingyouawake 
      brew install --cask spectacle 
      brew install --cask appcleaner 
      brew install --cask cheatsheet 
      brew install --cask docker 
      brew install --cask transmission 
      brew install --cask vlc 
      brew install --cask spotify 
      brew install --cask muzzle 
      brew install --cask hiddenbar 
      brew install --cask eul 
      brew install --cask ngrok  
      brew install --cask raycast 

      brew cleanup

    else
        echo "Error installing brew... brew + packages not installed."
    fi
    
    ## Setup Mac Settings
    source ~/.macos
fi


pecho "Done!" 2
